# Generated by Django 4.2.13 on 2024-06-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
