# Generated by Django 4.2.13 on 2024-06-11 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityServers',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('adress', models.CharField(max_length=255)),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=255)),
                ('date_register', models.DateTimeField(default=datetime.datetime(2024, 6, 11, 5, 2, 4, 147107, tzinfo=datetime.timezone.utc))),
                ('description', models.TextField()),
                ('code_service', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='SubSystems',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=255)),
                ('code_sub_system', models.CharField(max_length=255)),
            ],
            bases=('common.basemodel',),
        ),
    ]
