# Generated by Django 4.2.13 on 2024-06-11 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date_register',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 5, 2, 19, 709188, tzinfo=datetime.timezone.utc)),
        ),
    ]
