# Generated by Django 4.2.13 on 2024-06-15 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_adress_securityservers_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date_register',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 47, 7, 239364, tzinfo=datetime.timezone.utc)),
        ),
    ]
